spring.application.name=deskbooks-backend-java
server.address=127.0.0.1
server.port=${BACKEND_PORT:8765}
logging.level.root=WARN
spring.jackson.property-naming-strategy=SNAKE_CASE
spring.jackson.deserialization.fail-on-unknown-properties=false
